// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJf6eFCiniMm1hUDTifZyaxvKa8Ajg0o',
    appId: '1:92131514234:web:88e0159ee3da27dd2228c3',
    messagingSenderId: '92131514234',
    projectId: 'projectgt-9c838',
    authDomain: 'projectgt-9c838.firebaseapp.com',
    storageBucket: 'projectgt-9c838.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuG_abY9iUFmJqM9xmoB-0gtjMhWnjO8w',
    appId: '1:92131514234:android:32748fd8689c08512228c3',
    messagingSenderId: '92131514234',
    projectId: 'projectgt-9c838',
    storageBucket: 'projectgt-9c838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjw1adUeWnbKfj-Y1SizajQZIPWcOQQm0',
    appId: '1:92131514234:ios:8e51a18b2bf255322228c3',
    messagingSenderId: '92131514234',
    projectId: 'projectgt-9c838',
    storageBucket: 'projectgt-9c838.appspot.com',
    iosClientId: '92131514234-skb7ge9te0as32c2dd93vjca7ccqt2lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjw1adUeWnbKfj-Y1SizajQZIPWcOQQm0',
    appId: '1:92131514234:ios:8e51a18b2bf255322228c3',
    messagingSenderId: '92131514234',
    projectId: 'projectgt-9c838',
    storageBucket: 'projectgt-9c838.appspot.com',
    iosClientId: '92131514234-skb7ge9te0as32c2dd93vjca7ccqt2lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingFirebase',
  );
}
